development:
  adapter: postgresql
  encoding: utf8
  database: bcal_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: bcal_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: bcalg_production
  pool: 5
  username:
  password:
